"""added primary key for all table for innodb

Revision ID: 0a38b5dbcd8b
Revises: 484bcdefdbe9
Create Date: 2024-04-21 17:33:02.114227

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0a38b5dbcd8b'
down_revision = '484bcdefdbe9'
branch_labels = None
depends_on = None



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookmarked_post', schema=None) as batch_op:
        batch_op.create_primary_key(
            constraint_name="bookmarked_post_pk", columns=["post_id", "user_id"]
        )
        batch_op.alter_column('post_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('followed_tags', schema=None) as batch_op:
        batch_op.create_primary_key(
            constraint_name="followed_tags_pk", columns=["tag_id", "user_id"]
        )
        batch_op.alter_column('tag_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('followers', schema=None) as batch_op:
        batch_op.create_primary_key(
            constraint_name="followers_pk", columns=["follower_id", "followed_id"]
        )
        batch_op.alter_column('follower_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('followed_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('ignored_tags', schema=None) as batch_op:
        batch_op.create_primary_key(
            constraint_name="ignored_tags_pk", columns=["tag_id"]
        )
        batch_op.alter_column('tag_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_tags', schema=None) as batch_op:
        batch_op.alter_column('post_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('tag_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('ignored_tags', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('tag_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('followers', schema=None) as batch_op:
        batch_op.alter_column('followed_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('follower_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('followed_tags', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('tag_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('bookmarked_post', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('post_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
