"""added tags and post tags modles

Revision ID: 7059503392ff
Revises: 6092228cc420
Create Date: 2024-04-12 07:39:51.286580

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7059503392ff'
down_revision = '6092228cc420'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('post_tags',
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], )
    )
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('edited_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('body',
               existing_type=mysql.VARCHAR(length=140),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.drop_index('ix_post_timestamp')
        batch_op.create_index(batch_op.f('ix_post_created_at'), ['created_at'], unique=False)
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', mysql.DATETIME(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_post_created_at'))
        batch_op.create_index('ix_post_timestamp', ['timestamp'], unique=False)
        batch_op.alter_column('body',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=140),
               existing_nullable=True)
        batch_op.drop_column('edited_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('title')

    op.drop_table('post_tags')
    op.drop_table('tag')
    # ### end Alembic commands ###
