"""followed_tags, ignored_tags

Revision ID: b605aa9f466b
Revises: 7059503392ff
Create Date: 2024-04-15 11:09:39.198764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b605aa9f466b'
down_revision = '7059503392ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
